### ISSUE TITLE
GamePath string issue

### ISSUE THREAD

**Issue by fakedcake** [MrRean/Splat3D#1]
Hello,
when trying to choose a game path, splat3d always quits and says that my folder wouldn't contain the required files(but i think it has to do with the way it handles the string with the folder path).
this could be a error on my side, but i'm not very good at python, so i couldn't fix it for myself:

```
D:\WiiU\w\splatoon-nomod\splat3d>python main.py
Traceback (most recent call last):
  File "main.py", line 716, in <module>
    main()
  File "main.py", line 712, in main
    window = MainWindow()
  File "main.py", line 550, in __init__
    self.loadStageList()
  File "main.py", line 593, in loadStageList
    with open(self.gamePath+'\Pack\Static\Mush\MapInfo.byaml','rb') as f:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Python2.7, PyQT and PyOpenGL are working fine.

Thank you for your work, I'm struggling to do a working byaml-converter for quite some time.

**Comment by MrRean** [comment]
It's returning None, are you sure you have Pack/Static/Mush/MapInfo.byaml extracted?

**Comment by fakedcake** [comment]
Oh, I'm so stupid... I thought it extracts the SARC automatically, my bad :/

You may want to add that to your readme, maybe other people get confused too. 

Anyways, thank you very much!

**Comment by MrRean** [comment]
No problem, enjoy :)
